title: Journal
email: robertalberto350@gmail.com
description: >- 
  The real where my notes live
baseurl: "" 
url: "" 
github_username:  ra559
#For local development
theme: just-the-docs

#For github deployment
#remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

collections:
  code:
    permalink: "/:collection/:path"
    output: true
  linux:
    permalink: "/:collection/:path"
    output: true
  guides:
    permalink: "/collection/:path"
    output: true

just_the_docs:
  collections:
    code:
      name: Code
    linux:
      name: Linux
    guides:
      name: Guides

